### ISSUE TITLE
Next day chat send -> issue

### ISSUE THREAD

**Issue by Julian-Cole** [scenaristeur/solidarity#16]
If you have a browser open and come back to it the next day and send a message, any open clients don't catch any new messages;  i'm guessing this has something to do the new chat being posted into a new day folder and all the clients watching the previous day folder.  

A simple solution could be for each client to monitor the chat folder "day" and at midnight GMT and there-after keep checking to see if a new day folder is created by new chat; if it is then just refresh the chat.

**Comment by Julian-Cole** [comment]
@scenaristeur  any thoughts on how to mitigate this issue?    my solution seems to be too hacky;   could the websocket have stopped working after so long?

**Comment by scenaristeur** [comment]
Yes the websocket opens one listener to the last chat.ttl file. If you come back after 00:00 gmt ( 01:00) for me, I can post but it create a chat.ttl file in another folder due to the change of day. So the websocket isn't listening that new chat.ttl file. 
Refreshing the page updates the websocket traget. But we can't ask the websocket to update at midnight as the first next message can arrive later at 04:0/ or 08:00 and perhaps there will not be any message on this day. So the refresh needs a user action ( posting a message refresh the websocket or refresh the page) to get notified of the messages for the new day.
And perhaps the websocket disconnect after a long time ?

**Comment by Julian-Cole** [comment]
related to issue #30
